# Generated by Django 5.1.4 on 2025-01-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
