# Generated by Django 5.1.4 on 2025-01-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_alter_userprofile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.PositiveIntegerField(default=0)),
                ('goal', models.PositiveIntegerField(default=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_entries', to='calories.userprofile')),
            ],
        ),
    ]
