# Generated by Django 5.1.4 on 2025-01-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_calorieentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_activate',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
