# Generated by Django 5.1.4 on 2025-01-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_userprofile_is_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
