# Generated by Django 5.1.4 on 2025-01-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_rename_is_activate_userprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
    ]
